// Generated by gencpp from file image_processing/route_path.msg
// DO NOT EDIT!


#ifndef IMAGE_PROCESSING_MESSAGE_ROUTE_PATH_H
#define IMAGE_PROCESSING_MESSAGE_ROUTE_PATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace image_processing
{
template <class ContainerAllocator>
struct route_path_
{
  typedef route_path_<ContainerAllocator> Type;

  route_path_()
    : x()
    , y()  {
    }
  route_path_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _x_type;
  _x_type x;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::image_processing::route_path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_processing::route_path_<ContainerAllocator> const> ConstPtr;

}; // struct route_path_

typedef ::image_processing::route_path_<std::allocator<void> > route_path;

typedef boost::shared_ptr< ::image_processing::route_path > route_pathPtr;
typedef boost::shared_ptr< ::image_processing::route_path const> route_pathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_processing::route_path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_processing::route_path_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace image_processing

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'image_processing': ['/home/naveed/Documents/RMI/Soccerbots/soccer_ws_obs/src/image_processing/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::image_processing::route_path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_processing::route_path_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_processing::route_path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_processing::route_path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_processing::route_path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_processing::route_path_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_processing::route_path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d02d5b87dd0a8706354704c31a3c30e";
  }

  static const char* value(const ::image_processing::route_path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d02d5b87dd0a870ULL;
  static const uint64_t static_value2 = 0x6354704c31a3c30eULL;
};

template<class ContainerAllocator>
struct DataType< ::image_processing::route_path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_processing/route_path";
  }

  static const char* value(const ::image_processing::route_path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_processing::route_path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] x\n\
int32[] y\n\
";
  }

  static const char* value(const ::image_processing::route_path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_processing::route_path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct route_path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_processing::route_path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_processing::route_path_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_PROCESSING_MESSAGE_ROUTE_PATH_H
